[package]
name = "flairs33"
version = "0.1.0"
authors = ["ferrer"]
edition = "2018"

[profile.release]
overflow-checks = true

[dependencies]
decorum = "0.1"
rand = "0.7"
rand_distr = "0.2"
bitvec = "0.15"